# Generated by Django 4.1.1 on 2022-10-19 15:47

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, validators=[core.validators.valid_email_domain]),
        ),
    ]
