# Generated by Django 4.1.1 on 2022-10-25 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin', models.CharField(blank=True, db_column='LinkedIn', max_length=500, null=True)),
                ('telegram', models.CharField(blank=True, db_column='Telegram', max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, db_column='Facebook', max_length=100, null=True)),
                ('youtube', models.CharField(blank=True, db_column='YouTube', max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, db_column='Instagram', max_length=100, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
