# Generated by Django 4.1.1 on 2022-09-29 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_group_creation_date'),
        ('students', '0006_alter_student_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupST',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='groups.group')),
            ],
            bases=('groups.group',),
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.groupst', verbose_name='Group'),
        ),
    ]
