# Generated by Django 4.1.1 on 2022-09-29 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_groupst_student_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.DeleteModel(
            name='GroupST',
        ),
    ]
