# Generated by Django 4.1.1 on 2022-10-10 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_update_datetime'),
        ('students', '0008_remove_student_group_delete_groupst'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, default='2022-10-10 19:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='groups.group'),
        ),
        migrations.AddField(
            model_name='student',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
