# Generated by Django 4.1.1 on 2022-10-14 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_student_create_datetime_student_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
    ]
