# Generated by Django 4.1.1 on 2022-09-29 23:20

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(error_messages={'min_length': 'first_name field value less than two symbols'}, max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='first name')),
                ('last_name', models.CharField(error_messages={'min_length': 'last_name field value less than two symbols'}, max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='last name')),
                ('birthday', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(error_messages={'max_length': 'Phone number is too long, must be 12 digits!', 'min_length': 'Phone number is too short, must be 12 digits!'}, max_length=16, validators=[django.core.validators.MinLengthValidator(16)], verbose_name='phone number')),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
    ]
