# Generated by Django 4.1.1 on 2022-09-29 23:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.CharField(default='IT teacher', error_messages={'min_length': 'subject field value less than two symbols'}, max_length=200, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='subject'),
        ),
    ]
