# Generated by Django 4.1.1 on 2022-10-19 15:52

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teacher_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(error_messages={'value_error': 'Entered email domain not valid'}, max_length=254, validators=[core.validators.valid_email_domain]),
        ),
    ]
