# Generated by Django 4.1.1 on 2022-10-25 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_alter_teacher_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='occupation',
            field=models.CharField(default='Just a good programmer', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='working_place',
            field=models.CharField(blank=True, db_column='Company', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin', models.CharField(blank=True, db_column='LinkedIn', max_length=500, null=True)),
                ('telegram', models.CharField(blank=True, db_column='Telegram', max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, db_column='Facebook', max_length=100, null=True)),
                ('youtube', models.CharField(blank=True, db_column='YouTube', max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, db_column='Instagram', max_length=100, null=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='teachers.teacher')),
            ],
            options={
                'db_table': 'links',
                'abstract': False,
            },
        ),
    ]
