# Generated by Django 4.1.1 on 2022-10-25 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_teacher_occupation_teacher_working_place_sociallinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallinks',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_links', to='teachers.teacher'),
        ),
        migrations.AlterModelTable(
            name='sociallinks',
            table=None,
        ),
    ]
