# Generated by Django 4.1.1 on 2022-10-25 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_alter_sociallinks_teacher_alter_sociallinks_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallinks',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_links', to='teachers.teacher'),
        ),
    ]
