# Generated by Django 4.1.1 on 2022-10-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_alter_sociallinks_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
