# Generated by Django 4.1.1 on 2022-10-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_alter_teacher_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='facebook',
            field=models.CharField(blank=True, db_column='Facebook', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='instagram',
            field=models.CharField(blank=True, db_column='Instagram', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='linkedin',
            field=models.CharField(blank=True, db_column='LinkedIn', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='telegram',
            field=models.CharField(blank=True, db_column='Telegram', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='youtube',
            field=models.CharField(blank=True, db_column='YouTube', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='SocialLinks',
        ),
    ]
