# Generated by Django 4.1.1 on 2022-10-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0011_teacher_facebook_teacher_instagram_teacher_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='working_place',
            field=models.CharField(blank=True, db_column='company', max_length=50, null=True),
        ),
    ]
