# Generated by Django 4.1.1 on 2022-11-05 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('course_title', models.CharField(db_column='title', error_messages={'min_length': 'course title field value less than two symbols'}, max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Title')),
                ('course_place', models.CharField(choices=[(None, 'Choose a city'), ('k', 'Kyiv'), ('o', 'Odesa'), ('d', 'Dnieper'), ('h', 'Kharkiv'), ('l', 'Lviv'), ('v', 'Vinnitsa'), ('p', 'Poltava')], db_column='place', default=None, max_length=1, verbose_name='Location')),
                ('course_level', models.CharField(choices=[(None, 'Choose a level'), ('b', 'Basic'), ('a', 'Advanced'), ('p', 'Pro')], db_column='level', default=None, max_length=1, verbose_name='Level')),
                ('course_description', models.TextField(blank=True, db_column='description', null=True, verbose_name='Teaching plan')),
                ('course_duration', models.SmallIntegerField(db_column='duration', verbose_name='Duration')),
                ('course_start', models.DateField(blank=True, db_column='star_date', null=True, verbose_name='Start date')),
                ('course_price', models.IntegerField(db_column='price', verbose_name='Price')),
                ('course_price_currency', models.CharField(choices=[('h', 'UAH'), ('d', 'USD'), ('e', 'EURO')], db_column='currency', default='h', max_length=1, verbose_name='Currency')),
                ('course_enrollment_condition', models.IntegerField(blank=True, db_column='enroll', null=True, verbose_name='Conditions of enrollment')),
                ('course_graduation_condition', models.IntegerField(blank=True, db_column='graduate', null=True, verbose_name='Conditions of graduation')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
            },
        ),
    ]
