# Generated by Django 4.1.1 on 2022-10-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_level',
            field=models.CharField(choices=[(None, 'Choose a level'), ('b', 'Basic'), ('a', 'Advanced'), ('p', 'Pro')], db_column='level', default=None, max_length=1, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_place',
            field=models.CharField(choices=[(None, 'Choose a city'), ('k', 'Kyiv'), ('o', 'Odesa'), ('d', 'Dnieper'), ('h', 'Kharkiv'), ('l', 'Lviv'), ('v', 'Vinnitsa'), ('p', 'Poltava')], db_column='place', default=None, max_length=1, verbose_name='Location'),
        ),
    ]
