# Generated by Django 4.1.1 on 2022-09-22 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(error_messages={'min_length': 'group_name field value less than two symbols'}, max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Group name')),
                ('group_creation_date', models.DateField(auto_now_add=True)),
                ('group_description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Group description')),
            ],
        ),
    ]
