# Generated by Django 4.1.1 on 2022-09-23 08:49

import datetime
from django.db import migrations, models
import core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_creation_date',
            field=models.DateField(default=datetime.date.today, validators=[core.validators.validate_start_date]),
        ),
    ]
