# Generated by Django 4.1.1 on 2022-10-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_group_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
