# Generated by Django 4.1.1 on 2022-10-10 17:52

import core.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_update_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='start_date',
            field=models.DateField(default=datetime.datetime.utcnow),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_creation_date',
            field=models.DateField(auto_now_add=True, validators=[core.validators.validate_start_date]),
        ),
    ]
