# Generated by Django 4.1.1 on 2022-10-17 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_group_end_date_group_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_description',
        ),
    ]
